services:
  wwebjs:
    build:
      context: ./Bot
    volumes:
      - ./Bot:/app
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
      - wwebjs_cache:/app/.wwebjs_cache
    command: npm run dev
    restart: always

  qr:
    build: 
      context: ./QR
    ports:
      - "5000:5000"
    volumes:
      - ./QR:/app
    command: flask run --host=0.0.0.0

volumes:
  node_modules:
  wwebjs_auth:
  wwebjs_cache: