services:
  wwebjs:
    build:
      context: ./Bot
    volumes:
      - ./Bot:/app
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
      - wwebjs_cache:/app/.wwebjs_cache
    command: npm run dev
    depends_on:
      - mention
      - qr
    restart: always

  qr:
    build: 
      context: ./QR
    ports:
      - "5001:5000"
    volumes:
      - ./QR:/app
    command: flask run --host=0.0.0.0
    restart: always

  mention:
    build: 
      context: ./Mention
    volumes:
      - ./Mention:/app
      - node_modules_mention:/app/node_modules
    command: npm run dev
    depends_on:
      - mentiondb
    restart: always

  mentiondb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mention
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mention_db:/var/lib/mysql
    restart: always

  qr-backend:
    build: 
      context: ./Qr/Backend

  qr-frontend:
    build: 
      context: ./Qr/Frontend
    ports:
      - "5001:80"
    depends_on:
      - qr-backend

volumes:
  node_modules:
  wwebjs_auth:
  wwebjs_cache:
  mention_db:
  node_modules_mention:
