services:
  wwebjs:
    build:
      context: ./Bot
    volumes:
      - ./Bot:/app
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
      - wwebjs_cache:/app/.wwebjs_cache
    command: npm run dev
    depends_on:
      - mention
      - qr-frontend

  mention:
    build: 
      context: ./Mention
    depends_on:
      - mentiondb

  mentiondb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mention
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mention_db:/var/lib/mysql

  # mentiondbgui:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mentiondb
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - mentiondb

  qr-backend:
    build: 
      context: ./Qr/Backend

  qr-frontend:
    build: 
      context: ./Qr/Frontend
    ports:
      - "5001:80"
    depends_on:
      - qr-backend

volumes:
  node_modules:
  wwebjs_auth:
  wwebjs_cache:
  mention_db: